
"""
DBProj1-master Flask Application.
Auto-generated by FrameShift and enhanced for best practices, error handling, and readability.
"""

# Standard library imports
import logging

# Third-party imports
from flask import Flask, jsonify, current_app, request
from sqlalchemy.exc import SQLAlchemyError
from werkzeug.exceptions import HTTPException

# Local application imports
from config import config
from extensions import db, migrate

# Import blueprints and models to ensure they are registered with the application/SQLAlchemy
from DBApp.routes import DBApp_bp
from DBProj1.routes import DBProj1_bp
import DBApp.models  # Ensures SQLAlchemy models are loaded and registered with 'db'

def create_app(config_name='development'):
    """
    Application factory pattern to create and configure a Flask app.

    Args:
        config_name (str): The name of the configuration to use (e.g., 'development', 'testing', 'production').

    Returns:
        Flask: The configured Flask application instance.
    """
    app = Flask(__name__)

    # Configure logging
    # In production, use a proper logging configuration (e.g., to file, syslog, external service)
    if app.debug:
        app.logger.setLevel(logging.DEBUG)
    else:
        app.logger.setLevel(logging.INFO)
    # Basic console logger for development, more sophisticated handlers for production
    if not app.logger.handlers:
        handler = logging.StreamHandler()
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        handler.setFormatter(formatter)
        app.logger.addHandler(handler)

    app.logger.info(f"Starting Flask application with '{config_name}' configuration.")

    # Load configuration from specified environment
    try:
        app.config.from_object(config[config_name])
    except KeyError:
        app.logger.error(f"Configuration '{config_name}' not found. Defaulting to 'development'.")
        app.config.from_object(config['development'])
    except Exception as e:
        app.logger.critical(f"Failed to load application configuration: {e}", exc_info=True)
        raise # Re-raise to prevent app from starting with bad config

    # Initialize extensions
    # Ensure this is done after config is loaded but before blueprints/models might use them
    try:
        db.init_app(app)
        migrate.init_app(app, db)
        app.logger.info("SQLAlchemy and Flask-Migrate extensions initialized.")
    except Exception as e:
        app.logger.critical(f"Failed to initialize database extensions: {e}", exc_info=True)
        raise # Critical error, app likely cannot function without DB

    # Register blueprints
    app.register_blueprint(DBApp_bp, url_prefix='/DBApp')
    app.register_blueprint(DBProj1_bp, url_prefix='/DBProj1')
    app.logger.info("Blueprints DBApp_bp and DBProj1_bp registered.")

    # Create database tables within the application context
    # In a production environment, use Flask-Migrate or Alembic for database migrations
    # and avoid calling create_all() on app startup for schema management.
    with app.app_context():
        try:
            db.create_all()
            app.logger.info("Database tables ensured (created if they didn't exist).")
        except SQLAlchemyError as e:
            app.logger.critical(f"Database error during table creation: {e}", exc_info=True)
            # Depending on the application's criticality, you might want to raise here
            # to prevent the app from running without a functional database.
            raise
        except Exception as e:
            app.logger.critical(f"Unexpected error during database table creation: {e}", exc_info=True)
            raise

    # Register generic error handlers
    @app.errorhandler(404)
    def page_not_found(error):
        """Handle 404 Page Not Found errors, returning JSON."""
        current_app.logger.warning(f"404 Not Found: {request.path} - {error.description}")
        response = {
            "error": "Not Found",
            "message": error.description or "The requested URL was not found on the server."
        }
        return jsonify(response), 404

    @app.errorhandler(500)
    def internal_server_error(error):
        """Handle 500 Internal Server Error errors, returning JSON."""
        # Extract original exception if available for better logging
        original_exception = getattr(error, 'original_exception', None)
        if original_exception:
            current_app.logger.exception(f"500 Internal Server Error: {original_exception}")
            error_message = str(original_exception)
        else:
            current_app.logger.error(f"500 Internal Server Error: {error}")
            error_message = error.description or "An unexpected error occurred."

        response = {
            "error": "Internal Server Error",
            "message": "Something went wrong on the server."
        }
        # In debug mode, provide more detail
        if current_app.config.get('DEBUG', False):
            response["details"] = error_message
            if original_exception:
                response["traceback"] = "See logs for full traceback."
        return jsonify(response), 500

    @app.errorhandler(Exception)
    def handle_unhandled_exception(error):
        """Handle any other uncaught exceptions not specifically handled by other error handlers."""
        if isinstance(error, HTTPException):
            # Let Flask handle its own HTTP exceptions (like 404, 500 if not caught above)
            return error

        current_app.logger.exception(f"Unhandled Exception: {error}")
        response = {
            "error": "Internal Server Error",
            "message": "An unexpected error occurred."
        }
        if current_app.config.get('DEBUG', False):
            response["details"] = str(error)
        return jsonify(response), 500

    # Root route for the application
    @app.route('/')
    def index():
        """
        Renders a simple welcome message for the application's root URL.
        """
        current_app.logger.debug("Root route accessed.")
        return "Welcome to DBProj1-master!"

    return app

if __name__ == '__main__':
    # It's recommended to use 'flask run' via the command line for development,
    # which automatically handles debug and reloader. E.g.:
    # set FLASK_APP=app.py
    # set FLASK_ENV=development
    # flask run --host 0.0.0.0 --port 5000
    # However, running directly with app.run() is also valid for development.

    # Ensure 'development' configuration is used when running directly
    app = create_app('development')
    app.run(debug=True, host='0.0.0.0', port=5000)
